### ISSUE TITLE
Version 1.0.8

### ISSUE THREAD

**Issue by mspiderv** [bantikyan/icheck-bootstrap#2]
Can you please publish current master branch as 1.0.8 version ? Bower command `bower install icheck-bootstrap` downloads version 1.0.7 which does NOT contain all CSS classes.

**Comment by bantikyan** [comment]
Hello, just tested `bower install icheck-bootstrap` and can't see any issue, all classes are there. Can you check again?

**Comment by mspiderv** [comment]
When I run `bower install icheck-bootstrap --save` command, it will add this line to my `bower.json` file `"icheck-bootstrap": "^1.0.7"`. It will install [old styles](https://github.com/bantikyan/icheck-bootstrap/blob/1.0.7/icheck-bootstrap.css). When I manually edit `bower.json` to `"icheck-bootstrap": "master"` it will install [latest styles](https://github.com/bantikyan/icheck-bootstrap/blob/master/icheck-bootstrap.css). The problem is, old styles does not contain all classes, for example `icheck-success`. Sorry for my english, I hope you understand what I mean.

**Comment by bantikyan** [comment]
Thanks for your clarification. I have updated bower version 1.0.7 to point correct commit. Please can you check again?

**Comment by mspiderv** [comment]
I had to clear my bower's cache, but it works now. Thanks man :)
